name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: 'Build and publish container'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_REPOSITORY_OWNER }}
          password: ${{ secrets.PAT }}
          repository: ${{ env.GITHUB_REPOSITORY }}
          tags: latest
